version: '3.8'
x-database-common:
  environment:
    &mysql-environment
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
#    MYSQL_USER: ${MYSQL_USER}
#    MYSQL_PASSWORD: ${MYSQL_PASSWORD}

services:
  choisinsa-admin-app-kt:
    image: itchoi0429/choisinsa-admin-app-kt:1.0
    container_name: choisinsa-admin-app-kt
    build:
      context: .
      dockerfile: module-app-admin-kt/Dockerfile
    ports:
      - 8081:8081
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
    networks:
      - choisinsa-app-network
    depends_on:
      - choisinsa-mysql
      - choisinsa-redis
    restart: on-failure
  choisinsa-client-app-kt:
    image: itchoi0429/choisinsa-client-app-kt:1.0
    container_name: choisinsa-client-app-kt
    build:
      context: .
      dockerfile: module-app-choisinsa-kt/Dockerfile
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2GB
    networks:
      - choisinsa-app-network
    depends_on:
      - choisinsa-mysql
      - choisinsa-redis
    restart: on-failure
  choisinsa-mysql:
    image: itchoi0429/choisinsa-mysql:1.0
    container_name: choisinsa-mysql
    env_file:
      - .env
    ports:
      - ${MYSQL_MASTER_PORT}:${MYSQL_CLIENT_PORT}
    environment:
      <<: *mysql-environment
      MYSQL_SERVER_ID: ${MYSQL_MASTER_SERVER_ID}
      MYSQL_PORT: ${MYSQL_MASTER_PORT}
    networks:
      - choisinsa-app-network
    volumes:
      - choisinsa-mysql-volume:/var/lib/mysql
      - ./scripts/mysql-master-init.sh:/docker-entrypoint-initdb.d/mysql-master-init.sh
      - ./conf/mysql/master/my.cnf:/etc/mysql/my.cnf
    restart: always
#  choisinsa-mysql-slave-1:
#    image: itchoi0429/choisinsa-mysql:1.0
#    container_name: choisinsa-mysql-slave-1
#    env_file:
#      - .env
#    ports:
#      - ${MYSQL_SLAVE_1_PORT}:${MYSQL_CLIENT_PORT}
#    environment:
#      <<: *mysql-environment
#      MYSQL_SERVER_ID: ${MYSQL_SLAVE_1_SERVER_ID}
#      MYSQL_PORT: ${MYSQL_SLAVE_1_PORT}
#      MYSQL_MASTER_HOST: ${MYSQL_MASTER_HOST}
#    networks:
#      - choisinsa-app-network
#    volumes:
#      - choisinsa-mysql-slave1-volume:/var/lib/mysql
#      - ./scripts/mysql-slave-init.sh:/docker-entrypoint-initdb.d/mysql-slave-init.sh
#      - ./conf/mysql/slave/my.cnf:/etc/mysql/my.cnf
#    depends_on:
#      - choisinsa-mysql
#    restart: always
  choisinsa-mysql-slave-2:
    image: itchoi0429/choisinsa-mysql:1.0
    container_name: choisinsa-mysql-slave-2
    env_file:
      - .env
    ports:
      - ${MYSQL_SLAVE_2_PORT}:${MYSQL_CLIENT_PORT}
    environment:
      <<: *mysql-environment
      MYSQL_SERVER_ID: ${MYSQL_SLAVE_2_SERVER_ID}
      MYSQL_PORT: ${MYSQL_SLAVE_2_PORT}
      MYSQL_MASTER_HOST: ${MYSQL_MASTER_HOST}
    networks:
      - choisinsa-app-network
    volumes:
      - choisinsa-mysql-slave2-volume:/var/lib/mysql
      - ./scripts/mysql-slave-init.sh:/docker-entrypoint-initdb.d/mysql-slave-init.sh
      - ./conf/mysql/slave/my.cnf:/etc/mysql/my.cnf
    depends_on:
      - choisinsa-mysql
    restart: always
  choisinsa-redis:
    image: itchoi0429/choisinsa-redis:1.0
    container_name: choisinsa-redis
    env_file:
      - .env
    ports:
      - ${REDIS_CLIENT_PORT}:${REDIS_SERVER_PORT}
    networks:
      - choisinsa-app-network
    volumes:
      - choisinsa-redis-volume:/data
    restart: always

volumes:
  choisinsa-mysql-volume:
    name: choisinsa-mysql-volume
    external: true
  choisinsa-mysql-slave1-volume:
    name: choisinsa-mysql-slave1-volume
    external: true
  choisinsa-mysql-slave2-volume:
    name: choisinsa-mysql-slave2-volume
    external: true
  choisinsa-redis-volume:
    name: choisinsa-redis-volume
    external: true

networks:
  choisinsa-app-network:
    name: choisinsa-app-network
    external: true