name: Github Actions - Backend

on:
  push:
    branches:
      - main
    paths:
      - 'module-app-admin-kt'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # 가장 최신의 Ubuntu 러너 사용

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      # 현재 리포지토리 체크아웃

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      # Docker Buildx 설정

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Github Secret에서 Docker Hub 사용자 이름 조회
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Github Secret에서 Docker Hub 액세스 토큰 조회

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: . # build context
        file: ./module-app-admin-kt # Dockerfile 경로
        push: true # 이미지를 레지스트리에 푸시
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/module-app-admin-kt:${{ github.sha }} # commit id 활용 - 이미지 태그를 통해 어떤 소스로 반영된 버전인지 체크 가능
        platforms: linux/amd64,linux/arm64


